/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { HYDNBadge1__factory } from "./HYDNBadge1__factory";
export { HYDNBadge__factory } from "./HYDNBadge__factory";
