/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzepplin from "./openzepplin";
export type { HYDNSeal } from "./HYDNSeal";
export type { HYDNSealStorage } from "./HYDNSealStorage";
export type { openzepplin };
