/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";
import type {
  HYDNSealStorage,
  HYDNSealStorageInterface,
} from "../../contracts/HYDNSealStorage";

const _abi = [
  {
    inputs: [],
    name: "currentAuditId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "name",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class HYDNSealStorage__factory {
  static readonly abi = _abi;
  static createInterface(): HYDNSealStorageInterface {
    return new utils.Interface(_abi) as HYDNSealStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): HYDNSealStorage {
    return new Contract(address, _abi, signerOrProvider) as HYDNSealStorage;
  }
}
