/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc1155SupplyUpgradeableSol from "./ERC1155SupplyUpgradeable.sol";
export * as erc1155UpgradeableSol from "./ERC1155Upgradeable.sol";
