/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc1155SupplyUpgradeableSol from "./ERC1155SupplyUpgradeable.sol";
import type * as erc1155UpgradeableSol from "./ERC1155Upgradeable.sol";
export type { erc1155SupplyUpgradeableSol };
export type { erc1155UpgradeableSol };
